const express = require("express");
const router = express.Router();
const supabase = require("../services/supabaseClient");
const { authenticateUser } = require("../middleware/auth");

// POST /api/organizations/create - Create a new organization
router.post('/create', authenticateUser, async (req, res) => {
    console.log('=== POST /api/organizations/create called ===');
    console.log('Request body:', req.body);
    console.log('User from req.user:', req.user);
    
    const { name, description } = req.body;
    
    // Validation
    if (!name || name.trim() === '') {
        console.log('Validation failed: name is empty');
        return res.status(400).json({
            success: false,
            message: 'Organization name is required'
        });
    }
    
    try {
        const user_id = req.user?.id; // Get user ID from authenticated request
        
        console.log('Creating organization for user:', user_id);
        console.log('Organization name:', name);
        
        if (!user_id) {
            console.error('No user_id found in req.user');
            return res.status(401).json({
                success: false,
                message: 'User not authenticated'
            });
        }
        
        // Create the organization
        const { data: orgData, error: orgError } = await supabase
            .from('organizations')
            .insert({
                name: name.trim(),
                description: description ? description.trim() : null
                // org_id and created_at are auto-generated by the database
            })
            .select()
            .single();

        if (orgError) {
            console.error('Error creating organization:', orgError);
            return res.status(400).json({
                success: false,
                message: 'Failed to create organization',
                error: orgError.message
            });
        }

        console.log('Organization created successfully:', orgData);

        // Automatically add creator as admin member
        if (!orgData || !orgData.org_id) {
            return res.status(500).json({
                success: false,
                message: 'Organization was created but org_id is missing',
                error: 'Invalid organization data returned'
            });
        }

        console.log('Creating membership for user:', user_id, 'org_id:', orgData.org_id);
        
        const { data: membershipData, error: membershipError } = await supabase
            .from('organization_memberships')
            .insert({
                user_id: user_id,
                org_id: orgData.org_id,
                role: 'admin'
            })
            .select()
            .single();

        if (membershipError) {
            console.error('Failed to create membership for organization creator:', membershipError);
            console.error('Error details:', JSON.stringify(membershipError, null, 2));
            
            // Try to delete the organization if membership creation fails
            await supabase
                .from('organizations')
                .delete()
                .eq('org_id', orgData.org_id);
            
            return res.status(500).json({
                success: false,
                message: 'Organization created but failed to add you as admin. Organization has been removed.',
                error: membershipError.message,
                details: membershipError
            });
        }

        console.log('Membership created successfully:', membershipData);

        return res.status(201).json({
            success: true,
            message: 'Organization created successfully. You have been added as an admin.',
            organization: orgData,
            membership: membershipData
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while creating the organization',
            error: err.message
        });
    }
});

// GET /api/organizations - Get all organizations
router.get('/', async (req, res) => {
    try {
        const { data, error } = await supabase
            .from('organizations')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Failed to fetch organizations',
                error: error.message
            });
        }

        return res.json({
            success: true,
            organizations: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while fetching organizations',
            error: err.message
        });
    }
});

// GET /api/organizations/search?name=... - Search organization by name
router.get('/search', async (req, res) => {
    const { name } = req.query;
    
    if (!name || name.trim() === '') {
        return res.status(400).json({
            success: false,
            message: 'Organization name is required for search'
        });
    }
    
    try {
        const { data, error } = await supabase
            .from('organizations')
            .select('org_id, name, description')
            .ilike('name', `%${name.trim()}%`)
            .order('name', { ascending: true });

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Failed to search organizations',
                error: error.message
            });
        }

        return res.json({
            success: true,
            count: data.length,
            organizations: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while searching organizations',
            error: err.message
        });
    }
});

// GET /api/organizations/:id - Get a specific organization by org_id
router.get('/:id', async (req, res) => {
    const { id } = req.params;
    
    try {
        const { data, error } = await supabase
            .from('organizations')
            .select('*')
            .eq('org_id', id)
            .single();

        if (error) {
            return res.status(404).json({
                success: false,
                message: 'Organization not found',
                error: error.message
            });
        }

        return res.json({
            success: true,
            organization: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while fetching the organization',
            error: err.message
        });
    }
});

module.exports = router;
