const express = require("express");
const router = express.Router();
const supabase = require("../services/supabaseClient");
const { authenticateUser } = require("../middleware/auth");

// POST /api/organizations/create - Create a new organization
router.post('/create', authenticateUser, async (req, res) => {
    const { name, description } = req.body;
    
    // Validation
    if (!name || name.trim() === '') {
        return res.status(400).json({
            success: false,
            message: 'Organization name is required'
        });
    }
    
    try {
        const { data, error } = await supabase
            .from('organizations')
            .insert({
                name: name.trim(),
                description: description ? description.trim() : null
                // org_id and created_at are auto-generated by the database
            })
            .select()
            .single();

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Failed to create organization',
                error: error.message
            });
        }

        return res.status(201).json({
            success: true,
            message: 'Organization created successfully',
            organization: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while creating the organization',
            error: err.message
        });
    }
});

// GET /api/organizations - Get all organizations
router.get('/', async (req, res) => {
    try {
        const { data, error } = await supabase
            .from('organizations')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Failed to fetch organizations',
                error: error.message
            });
        }

        return res.json({
            success: true,
            organizations: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while fetching organizations',
            error: err.message
        });
    }
});

// GET /api/organizations/search?name=... - Search organization by name
router.get('/search', async (req, res) => {
    const { name } = req.query;
    
    if (!name || name.trim() === '') {
        return res.status(400).json({
            success: false,
            message: 'Organization name is required for search'
        });
    }
    
    try {
        const { data, error } = await supabase
            .from('organizations')
            .select('org_id, name, description')
            .ilike('name', `%${name.trim()}%`)
            .order('name', { ascending: true });

        if (error) {
            return res.status(400).json({
                success: false,
                message: 'Failed to search organizations',
                error: error.message
            });
        }

        return res.json({
            success: true,
            count: data.length,
            organizations: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while searching organizations',
            error: err.message
        });
    }
});

// GET /api/organizations/:id - Get a specific organization by org_id
router.get('/:id', async (req, res) => {
    const { id } = req.params;
    
    try {
        const { data, error } = await supabase
            .from('organizations')
            .select('*')
            .eq('org_id', id)
            .single();

        if (error) {
            return res.status(404).json({
                success: false,
                message: 'Organization not found',
                error: error.message
            });
        }

        return res.json({
            success: true,
            organization: data
        });
    } catch (err) {
        return res.status(500).json({
            success: false,
            message: 'An error occurred while fetching the organization',
            error: err.message
        });
    }
});

module.exports = router;
